### ISSUE TITLE
size

### ISSUE THREAD

**Issue by wycats** [wycats/nushell#17]
Like `wc`. Takes a list of strings as `$it` or a file as `$it`.

Produces an object with these fields:

- bytes
- lines
- words (maybe)
- max-length

And any other useful facilities from `wc`

**Comment by twe4ked** [comment]
I've started taking a crack at this but I noticed the name is conflicting with an Xcode CLI tool.

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/size
```
