### ISSUE TITLE
Ctrl-C should break running app

### ISSUE THREAD

**Issue by jonathandturner** [wycats/nushell#88]
Right now, ctrl-C will close nu altogether, rather than breaking the running app. Would be nice to just break the app and get back to the nu shell

**Comment by twe4ked** [comment]
Any pointers on how this should be implemented? I can't find a way to hook into `subprocess` to catch the signal. Should we be catching the signal another way ([this could work](https://github.com/BurntSushi/chan-signal#this-crate-has-reached-its-end-of-life-and-is-now-deprecated))? This might be over my head with my level of Rust knowledge for now, but if you can point me in the right way easily I can have a go :)

**Comment by jonathandturner** [comment]
Unsure. We might have to catch the signal in nu. If subprocess doesn't handle it natively, perhaps something like this would work? https://docs.rs/ctrlc/3.1.3/ctrlc/
